/gate/output/tree/enable

/gate/output/tree/hits/branches/runID/disable
/gate/output/tree/hits/branches/trackID/disable
/gate/output/tree/hits/branches/parentID/disable
/gate/output/tree/hits/branches/trackLocalTime/disable
/gate/output/tree/hits/branches/time/disable
/gate/output/tree/hits/branches/sourceID/disable
/gate/output/tree/hits/branches/primaryID/disable
/gate/output/tree/hits/branches/localPosX/disable
/gate/output/tree/hits/branches/localPosY/disable
/gate/output/tree/hits/branches/localPosZ/disable
/gate/output/tree/hits/branches/momDirX/disable
/gate/output/tree/hits/branches/momDirY/disable
/gate/output/tree/hits/branches/momDirZ/disable
/gate/output/tree/hits/branches/stepLength/disable
/gate/output/tree/hits/branches/trackLength/disable
/gate/output/tree/hits/branches/rotationAngle/disable
/gate/output/tree/hits/branches/axialPos/disable
/gate/output/tree/hits/branches/processName/disable
/gate/output/tree/hits/branches/comptVolName/disable
/gate/output/tree/hits/branches/RayleighVolName/disable
/gate/output/tree/hits/branches/volumeIDs/disable
/gate/output/tree/hits/branches/nPhantomCompton/disable
/gate/output/tree/hits/branches/nCrystalCompton/disable
/gate/output/tree/hits/branches/nPhantomRayleigh/disable
/gate/output/tree/hits/branches/nCrystalRayleigh/disable
#/gate/output/tree/hits/branches/gantryID/disable
#/gate/output/tree/hits/branches/rsectorID/disable
#/gate/output/tree/hits/branches/moduleID/disable
#/gate/output/tree/hits/branches/submoduleID/disable
#/gate/output/tree/hits/branches/crystalID/disable
#/gate/output/tree/hits/branches/layerID/disable
#/gate/output/tree/hits/branches/type/disable
/gate/output/tree/hits/branches/gammaType/disable
/gate/output/tree/hits/branches/decayType/disable
/gate/output/tree/hits/branches/sourceType/disable


/gate/output/tree/addFileName /homes/ymellak/Direct3G_f/O_Simu/Out{simu_number}/Sim_{number}.npy



/gate/output/tree/hits/enable
