# V I S U A L I S A T I O N

#/vis/open OGLSX 800x800

/vis/open OGLIQt

#/vis/viewer/set/viewpointThetaPhi 45 0  # To center
#/vis/viewer/set/viewpointThetaPhi 0 0  # To center
/vis/viewer/panTo 0 1 cm

#/vis/viewer/zoom 1
#########################################
####       View parallele to x       ####
#/vis/viewer/set/viewpointThetaPhi 270  0 # x- ==> x+
#/vis/viewer/panTo 45 0 cm

#/vis/viewer/set/viewpointThetaPhi 90  0 # x+ ==> x-
#/vis/viewer/panTo -45 0 cm

#/vis/viewer/zoom 2
#########################################
####       View parallele to y       #### There is a problem
#/vis/viewer/set/viewpointThetaPhi 90  89 # 
#/vis/viewer/panTo 0 -50 cm

#/vis/viewer/set/viewpointThetaPhi 270  90 # 
#/vis/viewer/panTo 0 -45 cm

#########################################
####       View parallele to z       ####
#/vis/viewer/set/viewpointThetaPhi 180  270 # z- ==> z+
#/vis/viewer/set/viewpointThetaPhi 0    90  # z+ ==> z-
#/vis/viewer/zoom 40
#########################################

/vis/modeling/trajectories/create/drawByParticleID # It's name by devault is "drawByParticleID-0"
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set nu_e yellow
/vis/modeling/trajectories/drawByParticleID-0/set Sc44[0.0] white
/vis/modeling/trajectories/drawByParticleID-0/set Sc44_2[0.0] white
/vis/modeling/trajectories/drawByParticleID-0/set Ca44[1157.0] green

/vis/viewer/set/style surface
/vis/drawVolume
#/vis/viewer/flush
/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
#/vis/scene/add/axes 600 -50 0 20 mm
/vis/viewer/refresh
#/vis/ogl/printEPS

# Il faut ajouter /vis/scene/add/trajectories

